apiVersion: v1
kind: Service
metadata:
  name: mongo-cfg-svc
spec:
  type: ClusterIP
  ports:
  - name: mongo
    port: 27018
  selector:
    app: mongo-cfg 

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-cfg
spec:
  selector:
    matchLabels:
      app: mongo-cfg
  replicas: 3
  serviceName: mongo-cfg-svc
  template:
    metadata:
      labels:
        app: mongo-cfg
    spec:
      containers:
      - name: mongo-cfg
        image: mongo:3.6.8
        ports:
        - name: mongo
          containerPort: 27018
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /data/db
        command: ["mongod"]
        args: ["--replSet", "cfg", "--dbpath", "/data/db", "--configsvr", "--bind_ip_all", "--port", "27018"]
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 1Gi
